name: "File Hash for cache"
description: 'Generates a hash of the given entry for cache key.'
author: 'KEINOS'

branding:
  icon: hash
  color: blue

inputs:
  path:
    description: 'A list of files that will be hashed.'
    required: true
  variant:
    description: 'A string to be hashed.'
    required: false

outputs:
  hash:
    description: 'The hash of the given entry.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.variant }}
